FROM php:7.3-apache

MAINTAINER Nombre <correo@unal.edu.co>

RUN requirements="zlib1g-dev libzip-dev zip libicu-dev git curl" \
    && apt-get update && apt-get install -y $requirements && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install intl \
    && docker-php-ext-install zip \
    &&  docker-php-ext-install mysqli \
    && apt-get purge --auto-remove -y

ENV WORDPRESS_DB_HOST=db
ENV WORDPRESS_DB_USER=USER
ENV WORDPRESS_DB_PASSWORD=PASS
ENV WORDPRESS_DB_NAME=wordpress

ADD ./wordpress/ /var/www/html/

RUN chown www-data /var/www/html


EXPOSE 80

#https://github.com/continuouspipe/php-example/tree/master/docker
#sudo docker build -t wordpress .
#sudo docker run --name wordpress -v ./wordpress/:/var/www/html -e WORDPRESS_DB_HOST=localhost -e WORDPRESS_DB_USER=ceapalaciosal -e WORDPRESS_DB_PASSWORD=c3s4r_p4l4c10s -e WORDPRESS_DB_NAME=Wordpress -p 80:80 --net=wordpress-net -d wordpress
